package fr.utbm.formationecole.entity;
// Generated 2019-11-6 18:50:13 by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int id;
     private String lastname;
     private String firstname;
     private String address;
     private String phone;
     private String email;
     private int courseSessionId;

    public Client() {
    }

    public Client(int id, String lastname, String firstname, String address, String phone, String email, int courseSessionId) {
       this.id = id;
       this.lastname = lastname;
       this.firstname = firstname;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.courseSessionId = courseSessionId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getCourseSessionId() {
        return this.courseSessionId;
    }
    
    public void setCourseSessionId(int courseSessionId) {
        this.courseSessionId = courseSessionId;
    }




}


