package fr.utbm.formationecole.entity;
// Generated 2019-11-6 18:50:13 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CourseSession generated by hbm2java
 */
public class CourseSession  implements java.io.Serializable {


     private Integer id;
     private Date startDate;
     private Date endDate;
     private Integer maxNumber;
     private String courseId;
     private int locationId;

    public CourseSession() {
    }

	
    public CourseSession(Date startDate, Date endDate, String courseId, int locationId) {
        this.startDate = startDate;
        this.endDate = endDate;
        this.courseId = courseId;
        this.locationId = locationId;
    }
    public CourseSession(Date startDate, Date endDate, Integer maxNumber, String courseId, int locationId) {
       this.startDate = startDate;
       this.endDate = endDate;
       this.maxNumber = maxNumber;
       this.courseId = courseId;
       this.locationId = locationId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Integer getMaxNumber() {
        return this.maxNumber;
    }
    
    public void setMaxNumber(Integer maxNumber) {
        this.maxNumber = maxNumber;
    }
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }




}


