package fr.utbm.formationecole.entity;
// Generated 2019-11-6 18:50:13 by Hibernate Tools 4.3.1



/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private String id;
     private String title;

    @Override
    public String toString() {
        return "Course{" + "id=" + id + ", title=" + title + '}';
    }

    public Course() {
    }

    public Course(String id, String title) {
       this.id = id;
       this.title = title;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


