package fr.utbm.formationecole.entity;
// Generated 2019-11-6 18:50:13 by Hibernate Tools 4.3.1



/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer id;
     private String city;

    public Location() {
    }

    public Location(String city) {
       this.city = city;
    }
   
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }


    @Override
    public String toString() {
        return "Location{" + "id=" + id + ", city=" + city + '}';
    }
    


}


