package fr.utbm.formationecole.entity;
// Generated 2019-11-6 18:50:13 by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer idUser;
     private String name;
     private String toto;

    public Users() {
    }

	
    public Users(String name) {
        this.name = name;
    }
    public Users(String name, String toto) {
       this.name = name;
       this.toto = toto;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getToto() {
        return this.toto;
    }
    
    public void setToto(String toto) {
        this.toto = toto;
    }




}


